version: '3.4'

services:
  apigateway.webapi:
    image: ${DOCKER_REGISTRY-}apigatewaywebapi
    build:
      context: .
      dockerfile: ApiGateway.WebApi/Dockerfile
    links:
      - warehouse.minimalapi
      - identity.minimalapi
    depends_on:
      - warehouse.minimalapi
      - identity.minimalapi
  warehouse.minimalapi:
    image: ${DOCKER_REGISTRY-}warehouseminimalapi
    build:
      context: .
      dockerfile: Warehouse.MinimalApi/Dockerfile
    links:
      - items.minimalapi
    depends_on:
      - items.minimalapi
  items.minimalapi:
    image: ${DOCKER_REGISTRY-}itemsminimalapi
    build:
      context: .
      dockerfile: Items.MinimalApi/Dockerfile
  identity.minimalapi:
    image: ${DOCKER_REGISTRY-}identityminimalapi
    build:
      context: .
      dockerfile: Identity.MinimalApi/Dockerfile

