apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
  namespace: warehouse-minimalapi
  labels:
    app: warehouse-minimalapi
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 0
  selector:
    matchLabels:
      service: warehouseminimalapi
  template:
    metadata:
      labels:
        app: warehouse-minimalapi
        service: warehouseminimalapi
    spec:
      containers:
      - name: warehouseminimalapi
        image: testregistry1999.azurecr.io/warehouseminimalapi
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 100m
            memory: 150Mi
        ports:
        - containerPort: 80
          protocol: TCP
        lifecycle:
          preStop:
            exec:
              command: ["sleep", "60"]          
---
apiVersion: v1
kind: Service
metadata:
  name: warehouseminimalapi
  namespace: warehouse-minimalapi
  labels:
    app: warehouse-minimalapi
    service: warehouseminimalapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: warehouseminimalapi           
